#######################################################################################
####log likelihood functions of observing different types of clusters followed by      ####         
####https://journals.plos.org/plospathogens/article?id=10.1371/journal.ppat.1004452####
####and https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7338915/                      ####
#######################################################################################

#parameters:
#s:number of source cases
#j:number of secondary cases directly (jointly) generated by the source cases (a single generation of spread)/ size of a cluster with unknown number of generations initiated by the source cases (clusters with unknown number of generation)
#Note sporadic cases were clusters with size equals to one, i.e., s equals to j 
#R0: reproduction number
#k: dispersion parameter
library(VGAM)
#--single-generation cluster--#
single_likFun=function(s,j,R0,k){ #here, j is the number of secondary cases (jointly) directly generated by s source cases.
  ll=lchoose(j+k*s-1,j)+k*s*(log(k)-log(R0+k))+j*(log(R0)-log(R0+k))
  return(sum(ll,na.rm=T))
}

#--cluster with unknown numder of generations--#
Multi_likFun=function(s,j,R0,k){ #here, j is the cluster (with unknown number of generations initialized by s source cases) size 
  if(length(s)==0) return(0)
  ll = log(k)+log(s)-log((k+1)*j-s)+lchoose((k+1)*j-s,j-s)+(j-s)*(log(R0)-log(k))-((k+1)*j-s)*log(1+R0/k)
  return(sum(ll,na.rm=T))
}
##########################################################################
###log likelihood function with censoring on the cluster size followed by ####
###https://academic.oup.com/biostatistics/article/4/2/279/245106  and ####   
###https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7338915/              ####
##########################################################################

#--single-generation cluster--#
single_cenFun=function(s,j,R0,k){ #here, j is the number of secondary cases (jointly) directly generated by s source cases.
  if(length(s)==0) return(0)
  censorl=0
  for (i in 1:length(s)){
    l=0
    if(s[i]==0||j[i]==0)next
    for (z in 0:(j[i]-1)){
      lli=single_likFun(s[i],z,R0,k)
      if(l<lli){
        l=-Inf
        break
      }
      l=l+log1mexp(-(lli-l))
    }
    if(!is.nan(l))censorl=censorl+l
  }
  return(censorl)
}

#--cluster with unknown numder of generations--#
multi_cenFun=function(s,j,R0,k){ #here, j is the cluster (with unknown number of generations initialized by s source cases) size 
  if(length(s)==0) return(0)
  censorl=0
  for (i in 1:length(s)){
    l=0
    if(s[i]==0||j[i]-s[i]==0)next
    for (z in s[i]:(j[i]-1)){
      lli=Multi_likFun(s[i],z,R0,k)
      if(l<lli){
        l=-Inf
        break
      }
      l=l+log1mexp(-(lli-l))
    }
    if(!is.nan(l))censorl=censorl+l
  }
  return(censorl)
}

